wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695941748.471238
    t:
      1:
      - 55
      - 86
      - 91
      - 95
      2:
      - 55
      - 86
      - 91
      - 95
      3:
      - 23
      4: 3.11.5
      5: 0.15.11
      8:
      - 4
      - 5
      13: darwin-arm64
